spring:
  application:
    name: rate-limiter
  data:
    redis:
      host: localhost
      port: 6379

  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://localhost:6379"
          connectTimeout: 5000
          timeout: 3000
          retryAttempts: 2

server:
  port: 8080